/* Shared by the offline editor and its Node.js tests. Coordinates are row-major. */
(function (root) {
  'use strict';
  const W = 50, H = 30, TILE = 20;
  function blank() {
    return {format: 'Por2D-map', version: 1, width: W, height: H, tileSize: TILE,
      name: '我的地图', commentary: '', tiles: Array.from({length: H}, () => Array(W).fill(0)), spawn: null, exit: null};
  }
  function parse(text) {
    const m = JSON.parse(text);
    if (!m || m.format !== 'Por2D-map' || m.version !== 1 || m.width !== W || m.height !== H || m.tileSize !== TILE)
      throw Error('不是支持的 Por2D 地图格式（需要版本 1、50×30 网格）。');
    if (typeof m.name !== 'string' || m.name.length > 80 || typeof m.commentary !== 'string' || m.commentary.length > 200)
      throw Error('地图名称或评语格式错误。');
    if (!Array.isArray(m.tiles) || m.tiles.length !== H || m.tiles.some(row => !Array.isArray(row) || row.length !== W || row.some(t => ![0,1,2].includes(t))))
      throw Error('方块数据错误：需要 30 行、每行 50 个 0/1/2。');
    for (const key of ['spawn', 'exit']) {
      const b = m[key];
      if (b !== null && (!b || !Number.isInteger(b.x) || !Number.isInteger(b.y) || b.x < 0 || b.x >= W || b.y < 0 || b.y >= H || ![0,1,2,3].includes(b.direction)))
        throw Error('出生点或过关点坐标 / 朝向无效。');
    }
    return {format: m.format, version: 1, width: W, height: H, tileSize: TILE,
      name: m.name, commentary: m.commentary, tiles: m.tiles.map(r => r.slice()),
      spawn: m.spawn && {...m.spawn}, exit: m.exit && {...m.exit}};
  }
  function bounds(b) {
    return {x: b.x * TILE + 1, y: b.y * TILE + 1, w: b.direction % 2 ? 58 : 18, h: b.direction % 2 ? 18 : 58};
  }
  function validate(m) {
    const errors = [];
    for (const [key, label] of [['spawn','出生点'], ['exit','过关点']]) {
      const b = m[key];
      if (!b) { errors.push('尚未设置' + label); continue; }
      const r = bounds(b);
      if (r.x <= 0 || r.y <= 0 || r.x + r.w >= W*TILE || r.y + r.h >= H*TILE) errors.push(label + '身体触碰或超出地图边界');
      let overlap = false;
      for (let y = b.y; y <= Math.floor((r.y+r.h-1)/TILE) && y < H; y++)
        for (let x = b.x; x <= Math.floor((r.x+r.w-1)/TILE) && x < W; x++) if (m.tiles[y][x]) overlap = true;
      if (overlap) errors.push(label + '身体与墙块重叠');
    }
    return errors;
  }
  function cpp(m) {
    const issues = validate(m);
    if (issues.length) throw Error(issues.join('；'));
    const quote = s => 'u8"' + s.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/[\u0000-\u001f\u007f]/g,c => '\\' + c.charCodeAt(0).toString(8).padStart(3,'0')) + '"';
    const body = b => { const r = bounds(b); return '{{' + r.x + ', ' + r.y + '}, Direction::' + ['Up','Right','Down','Left'][b.direction] + '}'; };
    const lines = ['// Generated by Por2D editor. Add this function to your level selection.', '#include "por2/level.hpp"', '', 'namespace por2 {', 'Level makeCustomLevel() {', '    Level level;', '    level.id = 1000;', '    level.name = ' + quote(m.name) + ';', '    level.commentary = ' + quote(m.commentary) + ';', '    level.spawn = ' + body(m.spawn) + ';', '    level.exit = Body' + body(m.exit) + ';'];
    for (let y=0;y<H;y++) for(let x=0;x<W;x++) {
      const t = m.tiles[y][x]; if (!t) continue;
      const start=x; while(x+1<W && m.tiles[y][x+1]===t) x++;
      lines.push(`    level.map.fill(Tile::${t===1?'PortalSurface':'Solid'}, ${start}, ${y}, ${x}, ${y});`);
    }
    return lines.concat('    return level;', '}', '} // namespace por2', '').join('\n');
  }
  function fillRectangle(m,a,b,tile) {
    if(![0,1,2].includes(tile))throw Error('Invalid tile');
    for(const c of [a,b])if(!Number.isInteger(c.x)||!Number.isInteger(c.y)||c.x<0||c.x>=W||c.y<0||c.y>=H)throw Error('Invalid rectangle');
    for(let y=Math.min(a.y,b.y);y<=Math.max(a.y,b.y);y++)
      for(let x=Math.min(a.x,b.x);x<=Math.max(a.x,b.x);x++)m.tiles[y][x]=tile;
  }
  const api = {W,H,TILE,blank,parse,bounds,validate,cpp,fillRectangle};
  if (typeof module !== 'undefined') module.exports = api;
  else root.MapModel = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
